context:
  version: "4.18.1"

package:
  name: markuplint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/markuplint/-/markuplint-${{ version }}.tgz
  sha256: d38be8e4d88e8268e85898c0c1bbee9300715a8168ddb26f07aca7a8cb675564

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - markuplint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Peace of mind in your markup - An HTML linter for all markup developers.
  homepage: https://github.com/markuplint/markuplint
  repository: https://github.com/markuplint/markuplint

extra:
  recipe-maintainers:
    - danielnachun
