context:
  version: "4.13.1"

package:
  name: markuplint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/markuplint/-/markuplint-${{ version }}.tgz
  sha256: 84191f46b43bae93c251b244d400e74ef9154227858681b8a0ac7e72cfdac77c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - markuplint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Peace of mind in your markup - An HTML linter for all markup developers.
  homepage: https://github.com/markuplint/markuplint
  repository: https://github.com/markuplint/markuplint

extra:
  recipe-maintainers:
    - danielnachun
