context:
  version: "4.18.0"

package:
  name: markuplint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/markuplint/-/markuplint-${{ version }}.tgz
  sha256: 63228b0daaf77fbdfb4f5ad82e3b419bf02fca417ba460f9e2915e3a45b01b7c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - markuplint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Peace of mind in your markup - An HTML linter for all markup developers.
  homepage: https://github.com/markuplint/markuplint
  repository: https://github.com/markuplint/markuplint

extra:
  recipe-maintainers:
    - danielnachun
