context:
  version: "5.0.1"

package:
  name: markuplint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/markuplint/-/markuplint-${{ version }}.tgz
  sha256: 273366bfbcd1e850ee6d0aa0581348edf27fbe94dab713d1e7e9bb220c83c325

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - markuplint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Peace of mind in your markup - An HTML linter for all markup developers.
  homepage: https://github.com/markuplint/markuplint
  repository: https://github.com/markuplint/markuplint

extra:
  recipe-maintainers:
    - danielnachun
